language: php

dist: trusty

addons:
  firefox: "31.0"

env:
  global:
    - COMPOSER_ROOT_VERSION=4.1.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL RECIPE_VERSION=~4.2.0 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=PGSQL RECIPE_VERSION=~4.2.0 PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=~4.2.0 PHPUNIT_COVERAGE_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=~4.2.0 BEHAT_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1 PHPCS_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 3G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:"$RECIPE_VERSION"
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.1.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

  # Start behat services
  - if [[ $BEHAT_TEST ]]; then echo 'SS_BASE_URL=http://localhost:8080/' >> .env; fi
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/selenium-server-standalone > artifacts/selenium.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &); fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @contentreview; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi

after_failure:
  - php ./framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/
